using OzelDers.Business.Interfaces;

namespace OzelDers.Business.Infrastructure.Payment;

public class FakePaymentService : IPaymentService
{
    // Simulates generating an Iyzico checkout URL
    public Task<string> InitiatePaymentAsync(decimal amount, string description, Guid userId)
    {
        // For development, we return a fake URL that directly returns a successful callback parameter
        // In real world, this calls Iyzico API to generate a form token and returns the PayUrl
        var fakeToken = Guid.NewGuid().ToString("N");
        var fakeUrl = $"https://sandbox-api.iyzipay.com/checkout?token={fakeToken}";
        return Task.FromResult(fakeUrl);
    }

    public Task<bool> VerifyPaymentCallbackAsync(string callbackData)
    {
        // For development, we just assume any callback is successful
        // In real world, this validates the HMAC signature or token generated by Iyzico
        return Task.FromResult(true);
    }
}
